// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usuarios.Context;

#nullable disable

namespace UsuariosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231130004346_PopularTabela")]
    partial class PopularTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Usuarios.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosAPI");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "MarcosDeOliveira@yahoo.com",
                            Idade = 23,
                            Nome = "Marcos de Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Email = "MariaDeOliveira@yahoo.com",
                            Idade = 23,
                            Nome = "Maria de Oliveira"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
